#!/bin/sh
# Para dar de alta la interfaz de la VPN. Usamos una netmask
# que englobe todas las subredes de cada nodo.

# Tomar la IP desde el archivo de configuración
# Equivale al primer Subnet del archivo de host
ip=$(cat /etc/tinc/${NETNAME}/ip.conf)

ifconfig $INTERFACE $ip netmask 255.255.255.0
